CREATE TABLE IF NOT EXISTS ContasBancarias (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    saldo DECIMAL(10, 2) DEFAULT 0.00,
    numeroConta VARCHAR(10) UNIQUE NOT NULL,
    senha VARCHAR(50) NOT NULL
);